# Generated by Django 3.1.2 on 2020-11-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='draft',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='api.proposaldraft'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
