# Generated by Django 3.1.2 on 2020-11-28 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_proposals', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_proposals', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='proposaldraft',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_drafts', to='api.employee'),
        ),
    ]
