# Generated by Django 3.1.2 on 2020-11-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_proposal_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='category',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
